language: R
sudo: false
cache: packages
addons:
  apt:
    update: true
    sources:
    - sourceline: 'ppa:opencpu/imagemagick'
    - 'ubuntu-toolchain-r-test'
    packages:
    - libv8-3.14-dev
    - libmagick++-dev
    - gcc-8
    - g++-8
    - gfortran-8
matrix:
  include:
  - os: linux
    r: release
    dist: trusty
    env:
    - BUILD_NAME=trusty_release
    - DETAILS="trusty release build"
    - R_CODECOV=true
env:
  global:
  - MAKEFLAGS="-j 2"
  - COMPILER=g++-8
  - CC=gcc-8
  - CXX=g++-8
  - NOT_CRAN=true
before_install:
  - mkdir -p ~/.R && touch ~/.R/Makevars
  - VER=-8
  - echo "CC=gcc$(VER)"    >> ~/.R/Makevars
  - echo "CXX=g++$(VER)"   >> ~/.R/Makevars
  - echo "CXX1X=g++$(VER)" >> ~/.R/Makevars
  - echo "FC=gfortran$(VER)"       >> ~/.R/Makevars
  - echo "F77=gfortran$(VER)"      >> ~/.R/Makevars
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 60 --slave /usr/bin/g++ g++ /usr/bin/g++-8
  - sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-8 60
warnings_are_errors: true
script:
- |
  travis_wait 20 R CMD build .
  travis_wait 20 R CMD check ALA4R*tar.gz
after_success:
- if [[ "${R_CODECOV}" ]]; then travis_wait 20 Rscript -e 'covr::codecov()'; fi
notifications:
  slack: atlaslivingaustralia:IPdEJ1wsRcGOF6PhqrgD7Ny4
  hipchat:
    rooms:
      secure: GcAsJ2ZSa1p3xGaYU1dqVXn1y08yRVTm/ADJJx3PU8s/SCk8CVjMcKGzBqPw66EYrYkBcaa+6vvFfJHyeJclbQgp9EIBxgqrvp4mNHxZPa9XVkTpCNNE7s26zkXmDZyH1UzD9o0AJfuEhwvCBawjckxArfAMSUgXZ3Ago/l8R24=
