language: R
sudo: false
cache: packages
addons:
  apt:
    update: true
    sources:
    - sourceline: 'ppa:opencpu/imagemagick'
    packages:
    - libv8-3.14-dev
    - libmagick++-dev
matrix:
  include:
  - os: linux
    r: release
    dist: trusty
    env:
    - BUILD_NAME=trusty_release
    - DETAILS="trusty release build"
    - R_CODECOV=true
env:
- NOT_CRAN=true
warnings_are_errors: true
script:
- |
  R CMD build .
  travis_wait 20 R CMD check ALA4R*tar.gz
before_install:
  - mkdir -p ~/.R/
  - echo "CXX14=g++ -std=c++1y -fPIC" >> ~/.R/Makevars
  - echo "CXX14FLAGS = -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -Wno-unused-local-typedefs -Wno-ignored-attributes -Wno-deprecated-declarations -Wno-attributes -O3" >> ~/.R/Makevars
after_success:
- if [[ "${R_CODECOV}" ]]; then travis_wait 20 Rscript -e 'covr::codecov()'; fi
notifications:
  slack: atlaslivingaustralia:IPdEJ1wsRcGOF6PhqrgD7Ny4
  hipchat:
    rooms:
      secure: GcAsJ2ZSa1p3xGaYU1dqVXn1y08yRVTm/ADJJx3PU8s/SCk8CVjMcKGzBqPw66EYrYkBcaa+6vvFfJHyeJclbQgp9EIBxgqrvp4mNHxZPa9XVkTpCNNE7s26zkXmDZyH1UzD9o0AJfuEhwvCBawjckxArfAMSUgXZ3Ago/l8R24=
