# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

addons:
  apt:
    #update: true
    packages:
      - libv8-3.14-dev

matrix:
    include:
        - os: linux
          r: release
          dist: trusty # 14.04
          env:
           - BUILD_NAME=trusty_release
           - DETAILS="trusty release build"

# set NOT_CRAN to true to ensure that skip_on_cran tests are run here
env:
  - NOT_CRAN=true

warnings_are_errors: true

script: 
  - |
    R CMD build .
    travis_wait 20 R CMD check ALA4R*tar.gz


after_success:
- travis_wait 20 Rscript -e 'covr::codecov()'
