language: R
sudo: false
cache: packages
addons:
  apt:
    packages:
    - libv8-3.14-dev
matrix:
  include:
  - os: linux
    r: release
    dist: trusty
    env:
    - BUILD_NAME=trusty_release
    - DETAILS="trusty release build"
    - R_CODECOV=true
env:
- NOT_CRAN=true
warnings_are_errors: true
script:
- |
  R CMD build .
  travis_wait 20 R CMD check ALA4R*tar.gz
after_success:
- if [[ "${R_CODECOV}" ]]; then travis_wait 20 Rscript -e 'covr::codecov()'; fi
notifications:
  hipchat:
    rooms:
      secure: GcAsJ2ZSa1p3xGaYU1dqVXn1y08yRVTm/ADJJx3PU8s/SCk8CVjMcKGzBqPw66EYrYkBcaa+6vvFfJHyeJclbQgp9EIBxgqrvp4mNHxZPa9XVkTpCNNE7s26zkXmDZyH1UzD9o0AJfuEhwvCBawjckxArfAMSUgXZ3Ago/l8R24=
