#' Generate a citation for occurrence data
#' 
#' @param data data.frame: occurrence data generated by `ala_occurrences`
#' @return string citation
#' @export ala_citation

ala_citation <- function(data) {
  if (is.na(attributes(data)$doi)) {
    stop("This dataset does not have a DOI. Please download again with 
         `mint_doi = TRUE` and then use `ala_citation.")
  }
  paste0("ALA occurrence download ", attributes(data)$doi, 
         ". Accessed from R with ALA4R",
         " (https://github.com/AtlasOfLivingAustralia/ALA4R/) on ",
         Sys.Date(), ".")
  
}