#' Counts for ALA records
#'
#' Takes filters in the same format as `ala_occurrences`, with an
#' additional break down by `breakdown`
#'
#' @param taxon_id string: single species ID or vector of species ids. Use
#' `ala_taxa()` to lookup species id.
#' @param filters data.frame: generated by `ala_filters()`
#' @param area string or sf object: restrict the search to an area. Can provide
#' sf object, or a wkt string. If the wkt string is too long, it may be
#' simplified.
#' @param breakdown field to breakdown the counts by
#' @param limit numeric: maximum number of categories to return. 20 by default.
#' @param caching logical: should the results be cached/use cache? Only used if
#' `breakdown` is supplied.
#' @return either single integer of total counts, or a dataframe of counts by
#' `breakdown` field, if specified.
#' @examples
#' # Count of records in the ALA
#' ala_counts()
#' # Counts by state and territory
#' ala_counts(breakdown = "state")
#' @export ala_counts

ala_counts <- function(taxon_id, filters, area, breakdown,
                       limit = 20, caching = FALSE) {

  query <- list()

  if (!missing(taxon_id)) {
    # should species id be validated?
    if (inherits(taxon_id, "data.frame") &&
        "taxon_concept_id" %in% colnames(taxon_id)) {
      taxon_id <- taxon_id$taxon_concept_id
    }
    assert_that(is.character(taxon_id))
    taxa_query <- build_taxa_query(taxon_id)
  } else {
    taxa_query <- NULL
  }

  # validate filters
  if (!missing(filters)) {
    assert_that(is.data.frame(filters))
    validate_filters(filters)
    filters$name <- dwc_to_ala(filters$name)
    filter_query <- build_filter_query(filters)
  } else {
    filter_query <- NULL
  }
  if (!is.null(filter_query) || !is.null(taxa_query)) {
    query$fq <- paste0("(", paste(c(taxa_query, filter_query),
                                  collapse = " AND "), ")")
  }

  if (!missing(area)) {
    # convert area to wkt if not already
    query$wkt <- build_area_query(area)
  }

  if (missing(breakdown)) {
    if (sum(nchar(query$fq), nchar(query$wkt), na.rm = TRUE) > 1948) {
      qid <- cache_params(query)
      query <- list(q = paste0("qid:", qid))
    }
    return(record_count(query))
  }

  # check facet is valid
  validate_facet(breakdown)
  breakdown <- dwc_to_ala(breakdown)
  query$facets <- breakdown
  query$flimit <- limit
  url <- getOption("ALA4R_server_config")$base_url_biocache
  path <- "ws/occurrence/facets"
  cache_file <- cache_filename(args = c(url, path, unlist(query), breakdown),
                               ext = ".csv")
  if (caching && file.exists(cache_file)) {
    return(read.csv(cache_file))
  }

  resp <- ala_GET(url, path, params = query)
  if (length(resp) < 1) {
    counts <- data.frame(
      name = as.character(),
      count = as.numeric()
    )
  } else {
    if (resp$count > limit) {
      warning("This field has ", resp$count, limit,
              " will be returned. Change `limit` to return more values.")
    }
    # parse out field value
    counts <- resp$fieldResult[[1]]
    value <- sapply(counts$fq, function(z) {
      sub('.*?"([^"]+)"', "\\1", z)
    }, USE.NAMES = FALSE)

    counts <- data.frame(
      name = value,
      count = counts$count
    )
  }
  if (caching) {
    write.csv(counts)
  }
  return(counts)
}

# get just the record count for a query
# handle too long queries in here?
record_count <- function(query) {
  query$pageSize <- 0
  url <- getOption("ALA4R_server_config")$base_url_biocache
  resp <- ala_GET(url, "ws/occurrences/search", query)
  resp$totalRecords
}

validate_facet <- function(facet) {
  if (!facet %in% c(ala_fields()$name, all_fields()$name)) {
    stop("\"", facet, "\" is not a valid breakdown field. ",
         "Use `ala_fields()` to get a list of valid options")
  }
}
